activesyncd linking: directly uses libeasclient
activesyncd uses eas_connection_error_quark() from libeasclient.
When using a linker with strict checking, linking fails with
"undefined reference to `eas_connection_error_quark'" because
previously libeasclient was only linked indirectly via libeas.