Tidy up int-to-pointer casting in progress hash table.
libeasmail.c: In function 'eas_mail_add_progress_info_to_table':
libeasmail.c:219:55: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
libeasmail.c: In function 'progress_signal_handler':
libeasmail.c:1081:87: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]

Since we're actually just trying to store the guint in the hash table
and it's never *really* used as a pointer, this is fine. Use GUINT_TO_POINTER
to make the compiler shut up.