Remove set-but-unused 'dtd' variable in eas_provision_msg_build_message()
eas-provision-msg.c: In function 'eas_provision_msg_build_message':
eas-provision-msg.c:120:10: error: variable 'dtd' set but not used [-Werror=unused-but-set-variable]