Use unused 'ret' variable in eas_folder_serialise()
eas-folder.c: In function 'eas_folder_serialise':
eas-folder.c:80:11: error: variable 'ret' set but not used [-Werror=unused-but-set-variable]

Use it, rather than recalculating it.