Revert "Cast the pointer token for the thread ID to a guint to remove the warning."
This reverts commit 645e38b6b1deaa55467b5f2b455f923ce736b572, which caused
build failure:
  CC     libeaslogger_la-eas-logger.lo
eas-logger.c: In function 'eas_logger':
eas-logger.c:40:83: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
eas-logger.c:43:76: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
eas-logger.c:46:73: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
eas-logger.c:49:71: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
eas-logger.c:56:82: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
eas-logger.c:59:75: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
eas-logger.c:62:72: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
eas-logger.c:65:70: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
cc1: some warnings being treated as errors