Remove unused 'child' variable
eas-connection.c: In function 'autodiscover_as_xml':
eas-connection.c:1428:18: error: variable 'child' set but not used [-Werror=unused-but-set-variable]