Remove set-but-unused 'leaf' variable from build_message() functions
eas-get-email-body-msg.c: In function 'eas_get_email_body_msg_build_message':
eas-get-email-body-msg.c:151:7: error: variable 'leaf' set but not used [-Werror=unused-but-set-variable]
eas-get-email-attachment-msg.c: In function 'eas_get_email_attachment_msg_build_message':
eas-get-email-attachment-msg.c:136:5: error: variable 'leaf' set but not used [-Werror=unused-but-set-variable]
eas-move-email-msg.c: In function 'eas_move_email_msg_build_message':
eas-move-email-msg.c:161:5: error: variable 'leaf' set but not used [-Werror=unused-but-set-variable]
eas-get-item-estimate-msg.c: In function 'eas_get_item_estimate_msg_build_message':
eas-get-item-estimate-msg.c:151:7: error: variable 'leaf' set but not used [-Werror=unused-but-set-variable]