Remove set-but-unused 'total' and 'unread' variables
camel-eas-folder.c: In function 'eas_refresh_info_sync':
camel-eas-folder.c:654:16: error: variable 'unread' set but not used [-Werror=unused-but-set-variable]
camel-eas-folder.c:654:9: error: variable 'total' set but not used [-Werror=unused-but-set-variable]