Mark dummy array in compile_time_assert as intentionally unused
eas-connection-errors.c: In function 'eas_connection_error_get_type':
eas-connection-errors.c:235:7: error: unused variable 'ASSERT_Error_Mapping_Out_Of_Date' [-Werror=unused-variable]