Use unused 'ret' variable in eas_provision_list_serialise()
eas-provision-list.c: In function 'eas_provision_list_serialise':
eas-provision-list.c:131:11: error: variable 'ret' set but not used [-Werror=unused-but-set-variable]

Use it, rather than recalculating it.