Remove set-but-unused 'ns' variable from eas_ping_msg_build_message()
eas-ping-msg.c: In function 'eas_ping_msg_build_message':
eas-ping-msg.c:111:9: error: variable 'ns' set but not used [-Werror=unused-but-set-variable]